### ISSUE TITLE
refresh secrets mounted as ENV Variables

### ISSUE THREAD

**Issue by ninjadude333** [hashicorp/vault-secrets-operator#103]
**Is your feature request related to a problem? Please describe.**
The operator is working great, but when mounting the secrets as ENV VARS, they will not be updated

**Describe the solution you'd like**
something like the reloader feature, that will trigger a rollout on secret change, or by any other way...

**Describe alternatives you've considered**
Reloader plugin combined with external-secret

**Comment by dnlopes** [comment]
This is already possible with the [rolloutRestartTarget](https://developer.hashicorp.com/vault/docs/platform/k8s/vso/api-reference#rolloutrestarttarget) for `Deployment`, `DaemonSet`, and `StatefulSet`.

The refresh is done by restarting the resources, which in practice will make the environment variables fetch the latest value on the K8s Secret.

**Comment by kschoche** [comment]
Hey @ninjadude333 - Thanks for filing this issue, as @dnlopes mentioned we'd recommend using the `rolloutRestartTarget` do do the refresh. If you find that doesn't work for your setup, or have additional feedback please feel free to let us know either by replying here or opening another issue.
Until then I'll go ahead and close this issue.
Cheers
