### ISSUE TITLE
namespace field in SecretSpecs

### ISSUE THREAD

**Issue by in0rdr** [hashicorp/vault-secrets-operator#117]
Thank you for creating this operator, I really enjoy using it so far.

I have  short question regarding the status of the [`namespace` field in the "SecretSpecs"](https://developer.hashicorp.com/vault/docs/platform/k8s/vso/api-reference).

I currently store the Vault secrets in the Vault root namespace. According to the documentation, the field configures "Namespace to get the secret from in Vault". However, in my experiments with the operator I could set this field to any value (like "abc", where there exists neither a Kubernetes nor a Vault namespace with that value).

First I was wondering, if the `namespace` field was used to configure the namespace of the `vaultAuthRef`. But it does not seem the case here.

Is the `namespace` field not implemented yet?

**Comment by tvoran** [comment]
Hi @in0rdr, good question. It looks like the vault namespace for a Vault*Secret is being set from the referenced VaultAuth CR currently, so we'll need to sort that out before GA.

**Comment by dnlopes** [comment]
> Hi @in0rdr, good question. It looks like the vault namespace for a Vault*Secret is being set from the referenced VaultAuth CR currently, so we'll need to sort that out before GA.

Taking this opportunity to ask: when is the GA date? Is it already defined?

Thanks.
