### ISSUE TITLE
Merge multiple vault secrets into one K8s secret

### ISSUE THREAD

**Issue by sebglon** [hashicorp/vault-secrets-operator#118]
**Is your feature request related to a problem? Please describe.**
The idea is to merge multiple Vault secret path in one K8S secret. this can help to inject Env Variable on many helm charts
example:
* harbor chart with the field `extraEnvVarsSecret ` that require only one K8s secret (https://github.com/bitnami/charts/blob/main/bitnami/harbor/values.yaml#L844)
* renovatebot

**Describe the solution you'd like**
Solution 1 can be to have a list of secret name to merge
Solution 2 can be to have template to define what key to inject form multiple secret name (this solution is more flexible and match with the vault agent injector templates)

**Comment by tdgeery** [comment]
I would also like to request some form of templating on the Kubernetes secret side.

We've been exploring the different operator options for secret integration and if you look at the external-secrets.io offering you'll see more of what we would like

[external-secrets.io#advanced-templating-v2|https://external-secrets.io/v0.8.1/guides/templating/]

**Comment by sebglon** [comment]
can be covered with this PR: https://github.com/hashicorp/vault-secrets-operator/pull/437

**Comment by benashz** [comment]
Closed with #437

**Comment by nia-potato** [comment]
Hey @benashz re-surfacing this issue, since this issue can now be solved with templating. i tried to write a template handle the use-case but could not get it working. do you know what would the template spec look like if we want to achieve this issues use case? 


- key1: path/to/secret1
- key2: path/to/secret2
- key3: path/to/secret3

final output after the template spec will only display one k8s secret: 


key1: secret1
key2: secret2
key3: secret3

**Comment by nia-potato** [comment]
i could not find the appropriate sprig function for this.

**Comment by hamishforbes** [comment]
I'm running into this too. Unless I'm missing something I don't think this is actually closed by transformations/templating at all?

I would like to be able to template multiple vault *keys* into a single file (i.e. a single key under `data` in the final Secret resource).

I'm trying to migrate from the Vault agent sidecar templating which has the `{{ with secret "PATH_HERE" }}` templating function. 
This makes it super easy to combine data from multiple vault secrets in a single file.

I have secrets that are common across all workloads and some that are specific to a particular app.
e.g.
```
secret/shared/foo
- field1: value1
- field2: value2

secret/private/app1
- fieldA: valueA

secret/private/app2
- fieldB: valueB
 ```

My apps are designed to consume a single source file for secrets, with vault agent templating I can fetch both keys and output them into a single file.
With VSO I have to have 2 Kubernetes Secret resources which have to be mounted as separate files and i'll need to make code changes to applications to support this, or find some other way of combining them at runtime
