### ISSUE TITLE
Ability to manage secrets across multiple kubernetes namespaces

### ISSUE THREAD

**Issue by njohnstone2** [hashicorp/vault-secrets-operator#136]
**Is your feature request related to a problem? Please describe.**
The output kubernetes secret from a sync operation is always stored in the namespace that contains the `VaultSecret*` custom resource. 

Theres two main problems with this:
1. I am unable to use the operator to manage secrets in scenarios where the secret is expected in a specific namespace.
2. a VaultConnection and VaultAuth resource needs to be created per kubernetes namespace that has vault managed secrets

**Describe the solution you'd like**
It would be good if the [Destination spec](https://developer.hashicorp.com/vault/docs/platform/k8s/vso/api-reference#destination) could support specifying the desired kubernetes namespace for the secret to be created in.

**Describe alternatives you've considered**
Creating `VaultConnection`, `VaultAuth` and `VaultSecret*` custom resources all in the desired kubernetes namespace works as expected but this means that you end up with duplicate Connection/Auth custom resources spread across multiple kubernetes namespaces

**Comment by TheLonelyGhost** [comment]
Sounds like it's similarly adjacent to the problem posed in #128 where you want to distribute a standard secret across all namespaces. Is that the intended goal? Or do you just want a dedicated namespace to handle distributing secrets to other namespaces?

In a similar vein of lowering overhead to configure a new k8s namespace, I could see following the `Cluster*` pattern (i.e., `ClusterRoleBinding` vs `Rolebinding`, `ClusterTask` vs `Task` in Tekton) for resources like `VaultConnection` so it can be configured once and referenced by any kube namespace in the cluster.

**Comment by ameyp** [comment]
>Or do you just want a dedicated namespace to handle distributing secrets to other namespaces?

That's the usecase I have in mind at least. I'd like to deploy the operator to the namespace containing my Vault ctluster, and have it be responsible for creating different secrets in different namespaces.

**Comment by njohnstone2** [comment]
> Or do you just want a dedicated namespace to handle distributing secrets to other namespaces?

This is my use case as well. Like @ameyp I also planned to use the default connection/auth from the helm values to manage my vault secrets.

> In a similar vein of lowering overhead to configure a new k8s namespace, I could see following the `Cluster*` pattern (i.e., `ClusterRoleBinding` vs `Rolebinding`, `ClusterTask` vs `Task` in Tekton) for resources like `VaultConnection` so it can be configured once and referenced by any kube namespace in the cluster.

I would be happy with this solution. I think this would require the `VaultSecret` resource to exist in the destination namespace but that is fine for my use case.

Let me know if you disagree but I see two possible configuration patterns:
1. Have all the  `VaultSecret` resources defined in a single namespace and the ability to specify a `destination` namespace
2. Define the `VaultSecret` resource in the `target` kubernetes namespace that references the `vaultAuthRef` in a separate namespace

**Comment by sebglon** [comment]
Using unique vaultAuthRef require to expose all your secret to the attached service account. and with this  vaultAuth every namespace can request Secret all secret. for me using a unique vaultauth accross namespaces is a security breach.

**Comment by mrjebabli** [comment]
@njohnstone2 @sebglon @njohnstone2 @TheLonelyGhost 
so for the moment, we can only deploy secret on 1 namespace? 
I'm using this link to try vault-secrets-operator 
after installing of the plugin using this tutos (https://developer.hashicorp.com/vault/tutorials/kubernetes/vault-secrets-operator#the-vault-secrets-operator)
helm install vault-secrets-operator hashicorp/vault-secrets-operator --version 0.1.0-beta -n vault --create-namespace --values vault/vault-operator-values.yaml
```
defaultAuthMethod:
enabled: true
# Vault namespace for the VaultAuthMethod CR
namespace: "app"
method: kubernetes
mount: kubernetes 
```
im only able to create secrets on the namespace app only, any idea how to add another namespace? 
![image](https://github.com/hashicorp/vault-secrets-operator/assets/64383508/384e5116-59ff-4368-8485-b8338ca3f41e)

**Comment by njohnstone2** [comment]
I'm currently working around the limitation by duplicating the 'VaultConnection' and 'VaultAuth' resources to each namespace that needs to sync secrets

**Comment by mrjebabli** [comment]
thanks @njohnstone2 , so for the moment we can use the operator only for one namespace? we can't duplicate the 'VaultConnection' and 'VaultAuth' manually?

**Comment by TheLonelyGhost** [comment]
To be clear, I see `VaultConnection` and `VaultAuth` as enabling end-users to use this operator instead of strictly kube admins. End-users are likely restricted to specific namespaces, so it makes sense to allow the resources to reside in a specific namespace.

From a kube admin standpoint, having it be cluster-wide (e.g., `ClusterVaultConnection` and `ClusterVaultAuth`) makes sense too. These would be building blocks for end-users that would scale for all present and future namespaces through one-time setup.

If choosing only one of those, I'm in favor of the cluster-wide implementation.

**Comment by allandegnan** [comment]
@togrulazizli - If you use the default service account like so:

```
---
defaultVaultConnection:
  enabled: true
  address: "http://vault.vault.svc.cluster.local:8200"
defaultAuthMethod:
  enabled: true
  kubernetes:
    role: ${vault-kube-auth-role}
    serviceAccount: default
    tokenAudiences:
    - vault
```

Then that already exists in every namespace.

The rest of my config is here: https://github.com/shutthegoatup/homelab and it appears to be working.

**Comment by nia-potato** [comment]
@allandegnan  

Hey allan, i tried your method of deploying vso to a kubnenetes cluster that then connects back a external vault cluster, and the connections seems to be working fine, however when i try directly applying secrets such as:
```
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  namespace: demo
  name: config
spec:
  mount: secret
  type: kv-v2
  name: myapp/config
  refreshAfter: 60s
  destination:
    create: true
    name: test-secret
```
I would get errors such as:
```
error: resource mapping not found for name: "config" namespace: "demo" from "secret2.yaml": no matches for kind "VaultStaticSecret" in version "secrets.hashicorp.com/v1beta1"
ensure CRDs are installed first
```

should we deploy secrets in a different way? I am assuming that since we already have ```defaultAuthMethod:``` block there is no need to re-apply something like the below since we are going through default service account auth. 

```
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: static-auth
  namespace: app
spec:
  method: kubernetes
  mount: test-dev
  kubernetes:
    role: vso
    serviceAccount: default
```
    
but it seems like on my end that if i dont apply VaultAuth, when applying secrets even when getting Connection Accepted in the vso logs i would get ```ensure CRDs are installed first```

**Comment by allandegnan** [comment]
> @allandegnan
> 
> Hey allan, i tried your method of deploying vso to a kubnenetes cluster that then connects back a external vault cluster, and the connections seems to be working fine, however when i try directly applying secrets such as:
> 
> ```
> apiVersion: secrets.hashicorp.com/v1beta1
> kind: VaultStaticSecret
> metadata:
>   namespace: demo
>   name: config
> spec:
>   mount: secret
>   type: kv-v2
>   name: myapp/config
>   refreshAfter: 60s
>   destination:
>     create: true
>     name: test-secret
> ```
> 
> I would get errors such as:
> 
> ```
> error: resource mapping not found for name: "config" namespace: "demo" from "secret2.yaml": no matches for kind "VaultStaticSecret" in version "secrets.hashicorp.com/v1beta1"
> ensure CRDs are installed first
> ```
> 
> should we deploy secrets in a different way? I am assuming that since we already have `defaultAuthMethod:` block there is no need to re-apply something like the below since we are going through default service account auth.
> 
> ```
> apiVersion: secrets.hashicorp.com/v1beta1
> kind: VaultAuth
> metadata:
>   name: static-auth
>   namespace: app
> spec:
>   method: kubernetes
>   mount: test-dev
>   kubernetes:
>     role: vso
>     serviceAccount: default
> ```
> 
> but it seems like on my end that if i dont apply VaultAuth, when applying secrets even when getting Connection Accepted in the vso logs i would get `ensure CRDs are installed first`

Assuming the CRD message is a red herring, I think your path is probably wrong.

My mount point is "kvv2" and my path is everything after that.

```
- apiVersion: secrets.hashicorp.com/v1beta1
  kind: VaultStaticSecret
  metadata:
    annotations:
      meta.helm.sh/release-name: arc-github-app
      meta.helm.sh/release-namespace: actions-runner-controller
    creationTimestamp: "2023-07-02T13:42:32Z"
    generation: 1
    labels:
      app: raw
      app.kubernetes.io/managed-by: Helm
      chart: raw-v0.3.2
      heritage: Helm
      release: arc-github-app
    name: arc-github-app
    namespace: actions-runner-controller
    resourceVersion: "8008422"
    uid: e1d23224-7df5-40a1-9e73-648e32cb2868
  spec:
    destination:
      create: true
      name: arc-github-app
    hmacSecretData: true
    mount: kvv2
    path: arc-github-app
    refreshAfter: 60s
    type: kv-v2
```

Here's a screenshot of my vault https://imgur.com/a/7WZ7dta

Hope that helps.

**Comment by ChristianCiach** [comment]
I am surprised that this issue has been closed as completed. It's still not possible to use a single, unique ServiceAccount across all namespaces of the cluster. 

Even when using this `VaultAuth`, you *still* need a separate `vault-default` ServiceAccount in each namespace:

```yaml
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: default
spec:
  vaultConnectionRef: default
  allowedNamespaces: ['*']
  method: jwt
  mount: jwt-external-services
  jwt:
    role: vso-default
    serviceAccount: vault-default
```
