### ISSUE TITLE
PKI secret should not Require commonName

### ISSUE THREAD

**Issue by Mason-776** [hashicorp/vault-secrets-operator#150]
**Describe the bug**
Use of the Common Name field has been [deprecated since 2000](https://datatracker.ietf.org/doc/html/rfc2818#section-3.1), and the requirement for a CN can be disabled in the Vault PKI backend role. Still, the Operator sets the field as Required. The Operator should only Require fields which are necessary to produce a valid Secret (in Vault and Kubernetes).

**To Reproduce**
1. Attempt to create a VaultPKISecret with no commonName value

Error: The VaultPKISecret "\<name>" is invalid: spec.commonName: Required value

**Expected behavior**
A certificate should be generated successfully without a Common Name.

**Environment**
* Kubernetes version: v1.25.9
  * Distribution or cloud vendor (OpenShift, EKS, GKE, AKS, etc.): kubeadm
  * Other configuration options or runtime services (istio, etc.):
* vault-secrets-operator version: v0.1.0-beta

**Comment by tvoran** [comment]
Hi @Mason-776, thanks for pointing this out! Indeed there is a [require_cn ](https://developer.hashicorp.com/vault/api-docs/secret/pki#require_cn) option, so I agree we should make the commonName optional in VaultPKISecret.

**Comment by benashz** [comment]
I think we may need to update the Vault API docs a well. They have https://developer.hashicorp.com/vault/api-docs/secret/pki#common_name as being required.

**Comment by benashz** [comment]
Opened for https://github.com/hashicorp/vault/pull/20403 for the Vault docs update.
