### ISSUE TITLE
Enable automatic recreation of accidentally deleted Kubernetes secrets.

### ISSUE THREAD

**Issue by sharique-masood** [hashicorp/vault-secrets-operator#231]
**Is your feature request related to a problem? Please describe.**
The current behaviour of the Vault Secret Operator does not recreate the secrets in Kubernetes if they are accidentally or intentionally deleted from the Kubernetes secrets after being synced.

**Describe the solution you'd like**
To address this issue, it would be beneficial to enhance the Vault Secret Operator's functionality to automatically recreate the secrets in Kubernetes when they are deleted. This would ensure the continuous availability and synchronisation of secrets between Vault and Kubernetes.

By implementing this enhancement, the Vault Secret Operator would become more resilient and provide a seamless experience, eliminating the need for manual intervention to recreate deleted secrets.

**Additional context**
Please consider incorporating this improvement into the Vault Secret Operator to enhance its reliability and usability.

**Comment by benashz** [comment]
Hi @sharique-masood , thanks for your feedback. With the v0.1.0-beta.1 release we added support for recreating the k8s Secret when the destination secret is deleted. We are not watching for a deletion event at this time, so we have to rely on a periodic reconciliation approach. Support for watching an "owned" k8s Secret will be added in future releases.

**Comment by benashz** [comment]
Relates to #228

**Comment by cjyar** [comment]
Seems like this was fixed by #532 in 0.4.3.

**Comment by benashz** [comment]
All VSO syncable secret controllers support secret deletion remediation.
