### ISSUE TITLE
[Chart] Pre-delete hook name can be >63 chars

### ISSUE THREAD

**Issue by fherenius** [hashicorp/vault-secrets-operator#260]
**Describe the bug**
The pre-delete hook in `deployment.yaml` can end up being longer than 63 characters. This causes some issues when trying to uninstall through helm.

Likely the error is related to: https://github.com/hashicorp/vault-secrets-operator/blob/17600c3836767d2837485f971686727800478a76/chart/templates/deployment.yaml#LL135C7-L135C7

In the above, `{{ include "chart.fullname" }}` will truncate to 63 characters, but then we're adding extra text at the end that might cause it to go over 63 characters. I think it might be labels injected by helm, but I'm not entirely sure.

The error I get is:
```
Error: warning: Hook pre-delete vault-secrets-operator/templates/deployment.yaml failed: Job.batch "vault-operator-vault-secrets-operator-pre-delete-controller-cleanup" is invalid: spec.template.labels: Invalid value: "vault-operator-vault-secrets-operator-pre-delete-controller-cleanup": must be no more than 63 characters
```

**To Reproduce**
1. Deploy the Vault Secrets Operator in a namespace with a long name, e.g. "vault-operator"
2. Try to uninstall it using `helm uninstall`

Application deployment:

```tf
resource "kubernetes_namespace" "vault-operator" {
  metadata {
    name = "vault-operator"
  }
}

resource "kubernetes_manifest" "vault-connection-default" {
  depends_on = [
    helm_release.vault-operator
  ]
  manifest = {
    apiVersion = "secrets.hashicorp.com/v1beta1"
    kind       = "VaultConnection"
    metadata = {
      namespace = kubernetes_namespace.vault-operator.metadata[0].name
      name = "default"
    }
    spec = {
      # Redacted 
    }
  }
}

resource "kubernetes_manifest" "vault-auth-default" {
  depends_on = [
    helm_release.vault-operator
  ]
  manifest = {
    apiVersion = "secrets.hashicorp.com/v1beta1"
    kind       = "VaultAuth"
    metadata = {
      namespace = kubernetes_namespace.vault-operator.metadata[0].name
      name = "default"
    }
    spec = {
      # Redacted
    }
  }
}

resource "helm_release" "vault-operator" {
  repository = "https://helm.releases.hashicorp.com"
  chart = "vault-secrets-operator"
  name  = "vault-operator"
  version = "0.1.0-rc.1"
  namespace = kubernetes_namespace.vault-operator.metadata[0].name
  atomic = true
  wait = true
  timeout = 10 * 60
  dependency_update = true
}
```

**Expected behavior**
Uninstall to work, regardless of namespace.

**Environment**
* Chart Version: 0.1.0-rc.1
* MicroK8s version: v1.25.10

**Comment by fherenius** [comment]
My apologies, after trying to get a fix working, it seems this was related to the `name` I'm giving the helm release. I don't think there's anything this chart can fix about it.

Closing the issue.

**Comment by sflanker** [comment]
I disagree that "there [isn't] anything this chart can fix about it." The chart has control of this name, as it is specified right here https://github.com/hashicorp/vault-secrets-operator/blob/main/chart/templates/deployment.yaml#L150:

```
  name: {{ include "chart.fullname" . }}-pre-delete-controller-cleanup
```

And with that girthy 30 character suffix, the user is left with only 33 for the name. And the default name being 22 characters with `vault-secrets-operator`, makes this a serious foot gun for anybody using a Flux HelmRelease to install this which results in a `chart.fullname` of `{{ .Release.Name }}-vault-secrets-operator`.

Given that the "chart.fullname" template already involves truncation, it doesn't seem unreasonable to truncate further to ensure this `Job` can be created.

You might ask "what about all the other resources that are created with the 'chart.fullname' template as part of their name?" But all of those resources are created when the chart is being installed, so the user gets immediate feedback that their chart name is too long. Whereas with this `Job` the user doesn't find out until they are unable to delete the HelmRelease and go sifting through their Flux logs.
