### ISSUE TITLE
Support imagePullSecrets in values.yaml

### ISSUE THREAD

**Issue by fvogl** [hashicorp/vault-secrets-operator#305]
Please include the possibility to configure imagePullSecrets as you have it in the vault helm chart.

**Comment by kschoche** [comment]
Hi @fvogl - Thanks for filing this issue!

We currently have `controller.imagePullSecrets` [here](https://github.com/hashicorp/vault-secrets-operator/blob/e82b7ea17f978246734f38e757d95d3dabf21fd6/chart/values.yaml#L63) in the helm chart for VSO which was added in #266 but hasn't been released yet.

Can you have a look at that and let me know if it meets your needs?

Thanks!
~Kyle

**Comment by fvogl** [comment]
Thanks @kschoche, that should do.
