### ISSUE TITLE
Unable to login to vault using approle methoda

### ISSUE THREAD

**Issue by themkarimi** [hashicorp/vault-secrets-operator#316]
**Describe the bug**
when we try to authenticated to an external instance of vault using vault operator and approle authentication method, we recieve this error:

2023-08-05T08:45:43Z	ERROR	Reconciler error	{"controller": "vaultstaticsecret", "controllerGroup": "secrets.hashicorp.com", "controllerKind": "VaultStaticSecret", "VaultStaticSecret": {"name":"vault-kv-app","namespace":"vault"}, "namespace": "vault", "name": "vault-kv-app", "reconcileID": "bc0fd069-4927-407a-85b3-2cdff2206783", "error": "Error making API request.\n\nNamespace: vault\nURL: PUT https://vault/auth/approle/role/stage-orbis/login\nCode: 403. Errors:\n\n* permission denied"}

**To Reproduce**
1. Install vault 
2. install vault secret operator in kubernetes and connect it to the previously installed vault instance
3. enable approle authentication on vault and generate ref-id and secret-id with a proper policy
4. enable approle authentication on secret operator helm chart
5. create a vaultstaticsecret

Application deployment:
vaules.yml
controller:
  replicas: 1
  kubeRbacProxy:
    image:
      repository: gcr.io/kubebuilder/kube-rbac-proxy
  manager:
    image:
      repository: hashicorp/vault-secrets-operator
    clientCache:
      persistenceModel: "none"
      storageEncryption:
        enabled: true
        vaultConnectionRef: default
        keyName: ""
        transitMount: ""
        method: kubernetes
        mount: kubernetes
        kubernetes:
          role: ""
  controllerConfigMapYaml:
    health:
      healthProbeBindAddress: :8081
    leaderElection:
      leaderElect: true
      resourceName: b0d477c0.hashicorp.com
    metrics:
      bindAddress: 127.0.0.1:8080
    webhook:
      port: 9443
  kubernetesClusterDomain: cluster.local
defaultVaultConnection:
  enabled: true
  address: "https://vault"
  skipTLSVerify: true
telemetry:
  serviceMonitor:
    enabled: true

defaultAuthMethod:
  enabled: true

  namespace: "vault"

  method: appRole

  mount: approle/role/stage

  appRole:
    roleId: "a5edb9e1-8c57-8b8a-43e7-44a7cdf4b667"
    secretRef: "vault-approl-secret"

**Expected behavior**
vault operator should be able to login to vault and get secrets.

**Environment**
* Kubernetes version: 1.26.5
  * Distribution or cloud vendor (OpenShift, EKS, GKE, AKS, etc.): Kube-Spray(On-premis)

* vault-secrets-operator version: 0.1.0

**Comment by vlaborie** [comment]
Hello,

I also use AppRole authentication, and it's working.

@themkarimi, it's not a bug with the vault-secrets-operator, but a misconfiguration:

You can see [in the documentation](https://developer.hashicorp.com/vault/docs/auth/approle#authentication) that the AppRole login endpoint is `/auth/approle/login`.
However, we can see from the error log you provided that you are trying to log in at `/auth/approle/role/stage-orbis/login`.

It's because you have defined `mount: approle/role/stage` instead of `mount: approle`.
