### ISSUE TITLE
Extending RolloutRestartTarget

### ISSUE THREAD

**Issue by 0x91** [hashicorp/vault-secrets-operator#338]
Are there any plans to extend RolloutRestartTarget to support CRDs such as the Argo project's Rollout object?

I couldn't see an immediately obvious way of doing this but I'd be happy to help contribute this if there's an appetite and given some pointers

**Comment by anas-domesticus** [comment]
It adds additional resources, but FYI I believe this can be achieved using Argo workflows, outside the scope of the vault operator -> https://argoproj.github.io/argo-workflows/
