### ISSUE TITLE
Add decodingStrategy for SecretSpec

### ISSUE THREAD

**Issue by nia-potato** [hashicorp/vault-secrets-operator#345]
**Is your feature request related to a problem? Please describe.**
There situations where we will be storing secrets in base64 format in vault ( such as byte data, hex data, data that are not json serializable) and that data would need to be stored as a base64 in vault, and then base64 decoded at the destination. external-secrets has [decodingStrategy](https://external-secrets.io/main/guides/decoding-strategy/) can we add something similar for this use case? 

**Describe the solution you'd like**
Allow individual secrets to be base64 decoded or default action of None. 

**Describe alternatives you've considered**
There are alternatives to let the application code do the decoding, but it would not make sense if a shared secret is use for multiple application, and each application would need to adapt their code to do the base64 decode.

**Comment by jpigree** [comment]
I have the same issue. I have base64 encoded binaries stored in Vault that I need to pull inside Kubernetes. Currently, VSO base64 encode them then write them inside K8s secrets.

Workarounds involve adding a base64 decode step either in code, entrypoints or as initcontainers.

**Comment by benashz** [comment]
We are planning to add template support in an upcoming VSO release. It will include the necessary encoding functions which should address the proposed use-case.

**Comment by nia-potato** [comment]
btw @benashz will it make it to the 0.3.0 release? its been blocking our migration.

**Comment by benashz** [comment]
@nia-potato it should go out in 0.4.0. Unfortunately, we can't provide an exact release date.

**Comment by Ameausoone** [comment]
This is exactly that we need at Decathlon, currently we use the templating with ExternalSecrets https://external-secrets.io/v0.4.2/guides-templating/

**Comment by nia-potato** [comment]
@benashz is there any possibility of squeezing this in the next release of 0.3.0? as it is blocking our migration. I believe it is a pretty critical feature, as it restricts the types of secrets we can store.

**Comment by mmalvik** [comment]
Also in need of this. Looking forward to 0.4.0 🙏

**Comment by opipenbe** [comment]
Any ETA on this one?
