### ISSUE TITLE
Add support for mTLS CA and CRL chain

### ISSUE THREAD

**Issue by sebglon** [hashicorp/vault-secrets-operator#452]
**Is your feature request related to a problem? Please describe.**
With Nginx,we need a secret with the CA an CRL chain for mTLS certificates.
For now we use a ricoberge resources with custom templating; but we need to migrate all our resources to  VSO.

**Describe the solution you'd like**
A possible solution is to have a new resources to cover this case.
Another solution is to add new arg on VaultPKISecret to provide to cover this case.

**Describe alternatives you've considered**
Alternative solution is to add templating on VaultStaticSecret to generate it.

**Additional context**

https://discuss.hashicorp.com/t/nginx-mtls-with-vault-secret-operator-how-to-manage-ca-cert-chain-and-crl/59474

**Comment by sebglon** [comment]
Maybe this PR can help: https://github.com/hashicorp/vault-secrets-operator/pull/437 ?

**Comment by benashz** [comment]
Closed with #437

**Comment by sebglon** [comment]
This issue is always present because we need 4 path from 2 PKI  to generate the secret
