### ISSUE TITLE
VSO template helpers override vault's helpers

### ISSUE THREAD

**Issue by ogirardot** [hashicorp/vault-secrets-operator#484]
**Describe the bug**
When using both VSO (0.4.0) and Vault (0.25.0) helm charts, the same helpers are defined in both helm charts without prefix related to their original projects. The main example is imagePullSecrets that end up creating a tricky situation in terms of lint : 

```
[ERROR] templates/: template: charts/vault/templates/tests/server-test.yaml:17:6: executing "charts/vault/templates/tests/server-test.yaml" at <include "imagePullSecrets" .>: error calling include: template: charts/vault-secrets-operator/templates/_helpers.tpl:153:15: executing "imagePullSecrets" at <.Values.controller.imagePullSecrets>: nil pointer evaluating interface {}.imagePullSecrets
```

An error that can only be fixed by defining in vault values : 

```
vault:
  controller: {}
```

**To Reproduce**
1. Use both in the same chart

**Expected behavior**
The helpers named templates should be prefixed with for example `vso.` so that the collision never happens.

**Comment by kschoche** [comment]
Hi @ogirardot - 
Thanks for filing this issue, I raised a simple draft PR that *should* address this, but before we merge that I'm curious why you're embedding both the vault and vault-secrets-operator into the same helm chart?

VSO should function just fine when installed without vault anywhere, and even if you were to configure VSO to point at a non-existent vault cluster it should be fine, it just wont sync anything until vault is online at that address.

**Comment by lee5i3** [comment]
Mentioned here https://github.com/hashicorp/vault-secrets-operator/issues/395

I'm also having this issue while using both vault and vault-secrets-operator in my chart, I'm using this with ArgoCD, we use a single chart with dependencies that way we can group the chart requirements together
