### ISSUE TITLE
VDS secret sync errors are not reported

### ISSUE THREAD

**Issue by adrianmoisey** [hashicorp/vault-secrets-operator#507]
**Describe the bug**
VSO is swallowing useful error messages when Vault is misconfigured.

We hit a bug in Vault, which seems to be related to this bug: https://github.com/aws/aws-sdk-go/issues/4989

When asking Vault for an AWS secret (which was configured using a file containing the credentials), vault would respond with a 400, and this error:
```
{"errors":["Error creating IAM user: NoCredentialProviders: no valid providers in chain. Deprecated.\n\tFor verbose messaging see aws.Config.CredentialsChainVerboseErrors"]}
```
 However, VSO never gave us an indication about why this failure occurred. There were no Events for the VaultDynamicSecret object, nor were there logs.

After some debugging I tracked it down to this piece of code: https://github.com/hashicorp/vault-secrets-operator/blob/28be7b3ca1bf8c49ab34c1a101bf2a3042b613c7/controllers/vaultdynamicsecret_controller.go#L210-L216

It seems that if an error of this type happens, VSO just retries, without bubbling the error up to the user in any way.

**To Reproduce**
1. Configure a Vault instance using a shared config file.
2. Setup VSO and a VaultDynamicSecret to get a secret
4. Watch for events and logs of an error, but don't get any.

Application deployment:

N/A
 
**Expected behavior**
Somehow VSO should indicate that there is an error, either with an event or logs

**Environment**
N/A
**Additional context**
N/A

**Comment by benashz** [comment]
Thanks for reporting this issue to us @adrianmoisey. All errors like the one you document should definitely be reported to the VSO user. We will put up a fix shortly.

**Comment by adrianmoisey** [comment]
I've found other easier ways to reproduce the error. If you need more details, I'm happy to write them down.

**Comment by adrianmoisey** [comment]
Thanks Ben!

Any chance https://github.com/hashicorp/vault-secrets-operator/issues/271 can get some attention?
