### ISSUE TITLE
Rollout Restart: support other Kinds

### ISSUE THREAD

**Issue by Jrc356** [hashicorp/vault-secrets-operator#529]
**Is your feature request related to a problem? Please describe.**
The only supported Kinds for rollout restart are `Deployment`, `StatefulSet`, and `DaemonSet`. However, I'd also like to use it with [ArgoRollouts](https://argoproj.github.io/rollouts/) and it would be nice to not be locked into only those 3 Kinds.

**Describe the solution you'd like**
The ability to specify a Kind outside of the 3 mentioned above

**Describe alternatives you've considered**
None

**Additional context**
From what I can tell, rollout restart works the same regardless of the Kind, except for [checking if a Deployment is paused](https://github.com/hashicorp/vault-secrets-operator/blob/main/internal/helpers/rollout_restart.go#L115), where it patches the annotation `vso.secrets.hashicorp.com/restartedAt` on the resource. I'm not sure what the best path here would be to check if a specified resource is "restartable." Perhaps a flag to allow unsupported types where, if enabled, it will patch the resource anyway with a warning?

**Comment by benashz** [comment]
Fixed with #702
