### ISSUE TITLE
OLM installation doesn't support setting flags for the operator

### ISSUE THREAD

**Issue by hoptical** [hashicorp/vault-secrets-operator#533]
**Is your feature request related to a problem? Please describe.**
I want to install `vault-secret-operator` through OLM ([OperatorHub](https://developer.hashicorp.com/vault/docs/platform/k8s/vso/openshift#operatorhub)). I need to set some parameters available in the helm chart, such as [PersistenceModel](https://developer.hashicorp.com/vault/docs/platform/k8s/vso/helm#v-controller-manager-clientcache-persistencemodel). However, since it's configured as a [flag](https://github.com/hashicorp/vault-secrets-operator/blob/8a8c25953771637bc498dc4ebcceb100b15349f1/chart/templates/deployment.yaml#L68C16-L68C16) for the operator and operator doesn't support [`ARGS` as environment variable](https://github.com/operator-framework/operator-lifecycle-manager/blob/cee062283539d08f25333bfa53b2963725e35914/doc/contributors/design-proposals/operator-config.md#scenario-enable-debug-logs-for-an-operator), it seems that we can't set such configuration in the OLM mode.

**Describe the solution you'd like**
Being able to set manager flags as environment variables. This can either be done via a separate env for every flag or supporting `ARGS` as an environment variable. 

**Describe alternatives you've considered**
Nothing specific.

**Additional context**

**Comment by tvoran** [comment]
Hi @hoptical, thanks for pointing this out. I think #551 should take care of this for OLM.
