### ISSUE TITLE
VSO v0.5.2 not available in helm

### ISSUE THREAD

**Issue by kalote** [hashicorp/vault-secrets-operator#655]
**Describe the bug**
The latest tag of VSO is not present on helm

**To Reproduce**
- `helm repo add hashicorp https://helm.releases.hashicorp.com`
- `helm repo update hashicorp`
- `helm search repo hashicorp/vault-secrets-operator`
```
NAME                            	CHART VERSION	APP VERSION	DESCRIPTION
hashicorp/vault-secrets-operator	0.5.1        	0.5.1      	Official Vault Secrets Operator Chart
```

**Expected behavior**
When a new release is done on the github repo, the new version should be available in helm.

**Comment by benashz** [comment]
Hi @kalote , thanks for reporting this issue. We are taking a closer look to see what may have happened on the release side of things.

**Comment by benashz** [comment]
We should be good to go now.

```
$ helm repo update hashicorp
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "hashicorp" chart repository
Update Complete. ⎈Happy Helming!⎈

$ helm search repo hashicorp/vault-secrets-operator
NAME                                    CHART VERSION   APP VERSION     DESCRIPTION
hashicorp/vault-secrets-operator        0.5.2           0.5.2           Official Vault Secrets Operator Chart
```
