### ISSUE TITLE
Avoid waiting for last lease to regenerate dynamic credentials

### ISSUE THREAD

**Issue by dnlopes** [hashicorp/vault-secrets-operator#99]
**Is your feature request related to a problem? Please describe.**

When using dynamic secrets (e.g., MySQL credentials), I have both defined a `lease-time` and `TTL` (let's assume a `1m` lease, `60m` TTL). The Operator will keep leasing without issues, until eventually it receives a `400 BadRequest` because he can't lease anymore. At this point, it will request new credentials and redeploy the app (I'm using the `rolloutRestartTargets` setting for this).

To me, this has potential to cause downtime if the app needs those credentials during the timeframe in which the TTL was reached and the app is being redeployed.

**Describe the solution you'd like**

I think the Operator has all the information needed to detect that the next lease will fail. When it detects it, he could generate a new credential and order the redeploy of the apps.

This would ensure that at any point in time, apps were using expired credentials.

Another improvement would be to also be able to apply this behavior earlier, to avoid waiting for the last lease. For instance, one could have a setting to force the credential regeneration at 75% of the TTL. This would give some extra slack if for some reason Vault is unable to generate the new credentials (it would have 25% of the TTL time to retry the operation, for instance).

**Describe alternatives you've considered**

None.

**Logs**
```
2023-03-31T11:55:15Z    DEBUG    events    Renewed lease, lease_id=database/creds/demo/nLJW1XkrEXftmUumvV83U8M0, horizon=841.645753ms    {"type": "Normal", "object": {"kind":"VaultDynamicSecret","namespace":"demo","name":"vault-dynamic-secret-1","uid":"5b6f3ab3-9cd4-4d27-bb44-e82179778df1","apiVersion":"secrets.hashicorp.com/v1alpha1","resourceVersion":"762"}, "reason": "SecretLeaseRenewal"}
2023-03-31T11:55:15Z    DEBUG    events    Could not renew lease, lease_id=database/creds/demo/nLJW1XkrEXftmUumvV83U8M0, err=Error making API request.

URL: PUT http://host.docker.internal:8200/v1/sys/leases/renew
Code: 400. Errors:

* failed to renew entry: resp: (*logical.Response)(nil) err: past the max TTL, cannot renew    {"type": "Warning", "object": {"kind":"VaultDynamicSecret","namespace":"demo","name":"vault-dynamic-secret-1","uid":"5b6f3ab3-9cd4-4d27-bb44-e82179778df1","apiVersion":"secrets.hashicorp.com/v1alpha1","resourceVersion":"762"}, "reason": "SecretLeaseRenewalError"}
2023-03-31T11:55:15Z    DEBUG    events    Rollout restart triggered for {Deployment demo-app-vso}    {"type": "Normal", "object": {"kind":"VaultDynamicSecret","namespace":"demo","name":"vault-dynamic-secret-1","uid":"5b6f3ab3-9cd4-4d27-bb44-e82179778df1","apiVersion":"secrets.hashicorp.com/v1alpha1","resourceVersion":"766"}, "reason": "RolloutRestartTriggered"}
2023-03-31T11:55:15Z    DEBUG    events    Secret synced, lease_id=database/creds/demo/a7NnGrthTTjghy1yehW0XLHJ, horizon=8.158461157s    {"type": "Normal", "object": {"kind":"VaultDynamicSecret","namespace":"demo","name":"vault-dynamic-secret-1","uid":"5b6f3ab3-9cd4-4d27-bb44-e82179778df1","apiVersion":"secrets.hashicorp.com/v1alpha1","resourceVersion":"766"}, "reason": "SecretRotated"}

```

**Comment by dnlopes** [comment]
So, I was able to replicate this issue with a dummy example:

1. deploy a container (`container 1`) that queries MySQL in loop
2. wait for the dynamic secret expires
3. check that `container 1` starts to have login issues
4. check that VSO regenerates a new credential and trigger the redeploy of the container (`container 2`)
5. check that `container 2` is able to login to MySQL properly.

This pattern repeats forever.

**Comment by dnlopes** [comment]
> Thanks @dnlopes! This is great feedback!

Glad to hear. Personally, for my use case, this is a blocker to expand our usage of dynamic secrets from K8s apps, as this effectively causes downtime on my runtime.

I hope a solution for this problem can be integrated in VSO soon.

PS: I'm thrilled with the launch of this component. I have been exploring other components like Banzai, but this one provides a much better UX for K8s developers with the Vault CRDs, and the refresh mechanism is awesome.

**Comment by dnlopes** [comment]
So, I was having a look at the code, and it seems it's not trivial to implement the changes I mentioned (or I missed something obvious). It seems Vault does not provide an easy way to know exactly when a given credential will expire. We have to rely on leases to perform those calculations, and even with that, it's not trivial, because apparently we only have access to the lease `expire-time` (and not the credential `maxTTL`).

In any case, a first approach would be to tell the Operator to rollout-restart if, during the current reconcile, it detects that the next horizon is after the lease TTL, ([code ref](https://github.com/hashicorp/vault-secrets-operator/blob/f617b4aa2f2572414d7039774ee1170f8f6e3a08/controllers/vaultdynamicsecret_controller.go#L147)) something like:

```go
horizon := computeHorizonWithJitter(leaseDuration)
r.Recorder.Eventf(o, corev1.EventTypeNormal, consts.ReasonSecretLeaseRenewal,
"Renewed lease, lease_id=%s, horizon=%s", leaseID, horizon)

// the next reconcile would run after the credential expire; let's rollout-restart earlier
if horizon > leaseDuration {
    doRolloutRestart = true
    r.Recorder.Eventf(o, corev1.EventTypeNormal, consts.ReasonSecretLeaseRenewal,
	    "credential will expire soon, triggering a rollout-restart, lease_id=%s", leaseID)
} else {
    return ctrl.Result{RequeueAfter: horizon}, nil
}
```
I wonder if this is enough, probably not; it seems fragile. 🤔 

PS: I was not able to run the integration tests; it seems Kind was unable to download some Docker images, but I didn't look into it further.

**Comment by inigohu** [comment]
It could be interesting to force the credential rotation before the `max_ttl` arrives to have time in case Vault is down for example.

Imagine the `max_ttl` is 2 weeks and I want to force the credential rotation in 1 week. This way if there is a problem with getting the credentials, I still have 1 week leeway to solve the problem.

**Comment by dnlopes** [comment]
I [opened a PR](https://github.com/hashicorp/vault-secrets-operator/pull/111) as an attempt to address this issue.

**Comment by adrianmoisey** [comment]
May be it's worth copying this logic: https://developer.hashicorp.com/vault/docs/agent/template#renewals-and-updating-secrets

> If a secret or token is renewable, Vault Agent will renew the secret after 2/3 of the secret's lease duration has elapsed.

**Comment by dnlopes** [comment]
> May be it's worth copying this logic: https://developer.hashicorp.com/vault/docs/agent/template#renewals-and-updating-secrets
> 
> > If a secret or token is renewable, Vault Agent will renew the secret after 2/3 of the secret's lease duration has elapsed.

Yep, makes sense. In the OP I mentioned that the `2/3` should be configurable, but I would be happy to have it hardcoded for now. 😄

**Comment by glerchundi** [comment]
This is a great feedback! And also a must to use dynamic secrets without depending too much on Vault when renewing and have unwanted downtimes.

It's also a good practice to start trying to renew before it expires. Let's encrypt does the same with certificates. Certificates are valid for 90 days but the next cycle starts renewing 30 days before it expires for another 90 days validity.

**Comment by tvoran** [comment]
Hi @dnlopes, for the dummy example you mentioned, can you include more detail about what the default and max ttl settings were for the mysql setup in Vault?

I think we'll probably end up doing renewals at 2/3 of the lease duration similar to Vault Agent, but I'd like to make sure we know what's going on in your use case.

**Comment by tvoran** [comment]
And just to note, the event log messages do seem to indicate that the rollout restart happens after the credentials are retrieved from Vault and synced to a k8s secret, but that's just because the "Secret synced" event is emitted [at the very end of the reconcile loop](https://github.com/hashicorp/vault-secrets-operator/blob/e1647127ea5234abf24e4a0d2db260141db17d7e/controllers/vaultdynamicsecret_controller.go#L193-L194). The new credential are indeed obtained from Vault, synced to a k8s secret, and then the rollout restart is triggered.

**Comment by dnlopes** [comment]
> Hi @dnlopes, for the dummy example you mentioned, can you include more detail about what the default and max ttl settings were for the mysql setup in Vault?

I can't recall the exact settgins I had, but I have used some combinations and all of them had the same issue. Maybe try with `default_ttl="30s" max_ttl="5m"`. This should replicate the problem.


> And just to note, the event log messages do seem to indicate that the rollout restart happens before the credentials are retrieved from Vault and synced to a k8s secret, but that's just because the "Secret synced" event is emitted [at the very end of the reconcile loop](https://github.com/hashicorp/vault-secrets-operator/blob/e1647127ea5234abf24e4a0d2db260141db17d7e/controllers/vaultdynamicsecret_controller.go#L193-L194). The new credentials are indeed obtained from Vault, synced to a k8s secret, and then the rollout restart is triggered. And we can make that ordering a little more clear in the events.

I didn't even notice this, but it could be misinterpreted by someone else.

> I think we'll probably end up doing renewals at 2/3 of the lease duration similar to Vault Agent, but I'd like to make sure we know what's going on in your use case.

That sounds like a good approach. Do you have any timeline for the fix to be released? As soon as you have a tag with the fix you can let me know so I can try to replicate the issue again.
